### ISSUE TITLE
Problems at the very first steps

### ISSUE THREAD

**Issue by gcanadav** [cetic/tinydtls#1]
Hello,
i am having problems trying to work with this dtls repository.
This is what i've done:

STEP 1. Download Contiki 2.7
STEP 2. Download this repository. Unzip it. "Autoreconf" it ( i think successfully because it creates a configure file). 
STEP 3. Move all to a new folder inside of contiki-2.7/apps called tinydtls.
STEP 4. "./configure --with-contiki" ( the log sais this:    configure: Contiki build prepared)
STEP 5. "make".

and i have these errors:
dtls.c: At function ‘dtls_peer_timeout’:
dtls.c:1402:9: error: ‘dtls_peer_t’ doesn't have a member called ‘ctx’
dtls.c:1402:9: error: ‘dtls_peer_t’ doesn't have a member called  ‘ctx’
dtls.c:1402:9: error: ‘dtls_peer_t’ doesn't have a member called  ‘ctx’
dtls.c:1402:9: error: ‘dtls_peer_t’ doesn't have a member called  ‘ctx’
dtls.c:1404:25: error: ‘dtls_peer_t’ doesn't have a member called  ‘ctx’

I've translated the logs, maybe something is not exactly the log in English, but more or less the problems are those^.

Regards!

**Comment by gcanadav** [comment]
After many hours of errors and more errors i have got my platform "working" but with RAM problems. Is there any posibility to progressively reduce the security and the ram uptake¿

Regards!

**Comment by lferasu** [comment]
Can you tell us how you solved the problem.
I am facing exactly the same error message when I make.
any help is appreciated
Regards,

**Comment by gcanadav** [comment]
Hello Iferasu

the problem was solved by defining CFLAGS += -DDTLS_CONN_TIMEOUT=10 at the
Makefile.
This is the dtls_peer_t struct:

typedef struct dtls_peer_t {
#ifndef WITH_CONTIKI
  UT_hash_handle hh;
#else /\* WITH_CONTIKI _/
  struct dtls_peer_t *next;
  struct ctimer timeout;
#if DTLS_CONN_TIMEOUT
  struct dtls_context_t *ctx;
#endif
#endif /_ WITH_CONTIKI */

  session_t session;         /**< peer address and local interface */

  dtls_peer_type role;       /**< denotes if this host is DTLS_CLIENT or
DTLS_SERVER */
  dtls_state_t state;        /**< DTLS engine state _/
  uint16 epoch;             /__< counter for cipher state changes_/
  uint48 rseq;             /**< sequence number of last record sent */

  dtls_hs_state_t hs_state;  /**< handshake protocol status */

  dtls_security_parameters_t security_params;
  dtls_handshake_parameters_t handshake_params;
} dtls_peer_t;

so if dtls_conn_timeout is not defined ( or 0) you have the problem.

Just one more thing, this was just one of a large amount of errors. And at
the end we did not manage to work with dtls. Be prepared :D.

Regards!

2014-07-21 18:40 GMT+02:00 lferasu notifications@github.com:

**Comment by laurentderu** [comment]
Defining DTLS_CONN_TIMEOUT is the responsibility of the application using tinydtls. We should add a default value however.

 Note that this version of tinydtls is already tailored for Contiki, so there is no need to use ./configure.

**Comment by Sabghh** [comment]
Hello,

If there is no need to use ./configure how to install this version of tinyDTLS on Contiki.
When I tried make; no makefile was found!
Also, for me, ./configure doesn't work as no configure file found and autoconf generates a bash error!
Thank you for your help or any information!

**Comment by laurentderu** [comment]
You don't need to install it, it's a ready to use module. You either add it as submodule or copy it under apps/ and reference if from your project Makefile.
See in 6lbr-demo for an example

**Comment by pksec** [comment]
Did anyone succeed in running the tinyDTLS on contiki ? with the example https://github.com/cetic/6lbr/wiki/Example-:-Dtls-Echo

## 

I succeeded with the following steps:  I created a simulation network with cooja ( with celtic 6lbr slip radio node)

## How to build the node
1. Building n examples/6lbr-demo with cooja. 
   make TARGET=wismote WITH_TINYDTLS=1 WITH_DTLSECHO=1
2. Connecting the 6LBR slip radio with the command available in examples/6lbr/test 
   sudo make launch-6lbr-router-1-cooja

## How to build the test client
1. I got the same error as mentioned in this thread, I tried to fix those errors by adding 
   CFLAGS += -DDTLS_CONN_TIMEOUT=10
   in the Makefile /apps/tinydtls
2. next I got the following error: 
   dtls-server.c:41:27: fatal error: net/uip-debug.h: No such file or directory
    #include "net/uip-debug.h"
                          ^
   **Fix**
    #include "net/ip/uip-debug.h" 
3. Next error: 
   dtls_time.c undefined reference to `clock_init'

**Comment by 14MCEN27** [comment]
hello

I extract the tinydtls-0.8.2.tar.gz file to ~/contiki/apps/tinydtls, then use ./configure -with-contiki, and edit both the /tinydtls-0.8.2/Makefile and examples/contiki/Makefile by adding APPS += tinydtls/aes tinydtls/sha2 tinydtls/ecc tinydtls.

But when i complie the example/dtls-client.c as sky mote or wismote mote in cooja simulator,it comes some error 

> make dtls-client.sky TARGET=sky

CC dtls-client.c
dtls-client.c:38:22:fatal error:tinydtls.h:no such file or directory
compilation terminated
process returned error code2
make:***[dtls-client.co]error 1

please help me ,

Regards,

**Comment by laurentderu** [comment]
Hello,

This repository is not the official TinyDTLS repository, it's a fork for the integrated version of 6LBR. Questions about TinyDTLS itself should be directed here : http://sourceforge.net/projects/tinydtls/

**Comment by 14MCEN27** [comment]
thank you so much for your help .but when i compile example/dtls-client.c
as cooja mote,it comes some error in the following picture.

On Mon, Dec 7, 2015 at 6:43 PM, Laurent Deru notifications@github.com
wrote:

> Closed #1 https://github.com/cetic/tinydtls/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cetic/tinydtls/issues/1#event-484365286.

## 

Foram Suthar
TA   CSE(NT)  Dept,
Institute of Technology,
Nirma University,  Ahmedabad

**Comment by Ankita-Jain09** [comment]
Hello,
I am trying to use tinydtls in contiki-2.7.
I extracted tinydtls-0.8.2 to contiki/apps/tinydtls , then used ./configure --with-contiki and then make but I am getting the following errors.
Please help me solve them, any help would be appreciated.
![new_pictursse](https://cloud.githubusercontent.com/assets/27188302/26437459/3cb59c48-40d2-11e7-912c-62a028e0de00.jpg)

**Comment by honestyhz** [comment]
hello
i work with tinydtls-0.8.2, any body know how should i change it so multiple clients can handshake with single server?
thanks
